language: python
matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      sudo: required
      language: generic
addons:
  apt:
    packages:
    - libsnappy-dev

# command to install dependencies
# Manually install python on osx
install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update;
      brew install snappy;
      PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.2;
      pyenv local 3.5.2;
      pyenv global 3.5.2;
      $(pyenv root)/shims/python -m venv venv;
      source venv/bin/activate;
      pip install 'setuptools>=38.5'
      pip install -e '.[dist]'
      pip install -e '.[test]'
  else
      pip install 'setuptools>=38.5'
      pip install -e '.[dist]'
      pip install -e '.[test]'
      if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then
          pip install --upgrade https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
      fi
  fi

# command to build
script:
  - py.test -m 'not (requires_server or external_resources)'
  - python setup.py dist
deploy:
  - provider: script
    script: BRANCH=$TRAVIS_BRANCH python setup.py deploy
    skip_cleanup: true
    on:
      all_branches: true
      condition: |
        ( $TRAVIS_PYTHON_VERSION == '3.6' ) || ( $TRAVIS_OS_NAME == 'osx' )
  - provider: pypi
    user: lordi
    password:
      secure: Tuf6fL62LvkmDfYWmdPH1VMLBV0mNeBWcEJJcQd1VN4vtQnFsmq9eU1CB9tAajpazBTNQBj9gfgcdBSBbT5Wg9rcSGbNFXlWEDxvTdVokpRzByCQNR2NEbGuoQF4pcSD8VSTO6blVDM+XVccSSMIzJJbINulZFiveNgZj3lWMa8B+AqTr+ACuekeU5V1VfkmJ1pWVhwnJ4kj75dsRV7BFtZrGoA5UsuVu4tEUDbUQYuMEOEDbFJ2/uka8KvKcaoFvs5kToiohSH0t+umtnXZe3T+S6Xdn9bw97yyAEwE+7U1UlqXj+uOvtjvtFs+Ai1F40MEVGd2GjC7H5NP4HknrKl+k1VhYEyjCV8SvXBryEvrYYjgYmAET2dMu+AmsOzGcjwV4TT7YhQ0F75aZb8HKnJOX7/UQeUSNhBZIw5NBnrDyPf+5t+FrUJdjtALxrMlhM5nEjm9rCYwo2r+f6+dKiibg9uVej+RbesTJNBHBorbzZBe5B7EFadmfUTRM74cH02OTm8PvaCfrp9jDNfQ3WombUqwSyQIm+EX83BC89sws+ixcmcnVXJLwaK+y8JP+0zpe7YinesvV5rfntH6WBBjVNAVYbi2LIbEfcRMAHe29tKvf+nRcS5KtWCtqJol+w5NxpHcjWYF60xuesjiS6KjneZAoCstJJbyXfc+8+4=
    on:
      tags: true
      condition: |
        ( $TRAVIS_PYTHON_VERSION == '3.6' ) && ( $TRAVIS_OS_NAME == 'linux' )

