language: python
matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: osx
      sudo: required
      language: generic
addons:
  apt:
    packages:
    - libsnappy-dev

# command to install dependencies
# Manually install python on osx
install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      brew update;
      brew install python3;
      brew install snappy;
      python3 -m venv venv;
      source venv/bin/activate;
      pip install -e '.[dist]'
  else
      pip install -e '.[dist]'
  fi

# command to build
script: python setup.py dist

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file:
    - "dist/syncrypt-*.darwin-x86_64.zip"
    - "dist/syncrypt-*.linux-x86_64.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
